### ISSUE TITLE
well-travelled script: vcf_tab_to_fasta_alignment.pl

### ISSUE THREAD

**Issue by rafalcode** [bergeycm/NGS-map#2]
Hi Christina,

I think since you published this script 2012 time, it has travelled quite a bit  ... I found it copied into a copy of vcftools lying around our lab in Scotland here.

What happens in these occasions is that small ad-hoc edits are made, sometimes in a rush, and the output may be different to what you as author intended. For such situations, and dspite it being a small script as you call it, it could benefit from more inline documentation so that people will edit more wisely, and less in a rush.

So this isn't a bug or an issue as such, rather a heads-up that your script is actually pretty famous, and it may be an idea to look at the old version posted on google code and to include a link to the latest version (which I assume is in this repository) and to advise users to update.

I'll fork it and include my own notes for good measure.

Cheers / Ramon.

**Comment by bergeycm** [comment]
Since Google Code has shut down, I've migrated the repository you're referring to to GitHub. It can be found at https://github.com/bergeycm/vcf-tab-to-fasta/ . There are inline comments throughout and a README, so I'll close this.
